//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANGHOA
    {
        public string BARCODE { get; set; }
        public string TENHH { get; set; }
        public string TENTAT { get; set; }
        public string MADVT { get; set; }
        public Nullable<int> DONGIA { get; set; }
        public Nullable<int> MANCC { get; set; }
        public Nullable<int> MAXX { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<bool> DISABLED { get; set; }
    }
}
