//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TONKHO
    {
        public System.Guid KHOA { get; set; }
        public Nullable<int> NAMKY { get; set; }
        public Nullable<int> NAM { get; set; }
        public Nullable<int> KY { get; set; }
        public string MADVI { get; set; }
        public Nullable<int> LUONG_DAU { get; set; }
        public Nullable<int> LUONG_NHAP { get; set; }
        public Nullable<int> LUONG_XUAT { get; set; }
        public Nullable<int> LUONG_CUOI { get; set; }
        public Nullable<double> THANH_TIEN { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
    }
}
